luna = {}
---@return table
luna.build = function()
	local theme = {
		-- PATCH_OPEN
Normal = {fg = "#DEBEEF", bg = "#452753"},
MiniStatuslineFilename = {link = "Normal"},
StatusLine = {link = "Normal"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#CCDA95"},
Boolean = {link = "Character"},
Float = {link = "Character"},
Number = {link = "Character"},
["@character"] = {link = "Character"},
ColorColumn = {bg = "#673B7D"},
Comment = {fg = "#826490", italic = true},
LspCodeLens = {link = "Comment"},
LspCodeLensSeparator = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Conceal = {fg = "#826490"},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#EFBB43"},
["@constant"] = {link = "Constant"},
CurSearch = {fg = "#563168", bg = "#F4D07C"},
IncSearch = {link = "CurSearch"},
Cursor = {fg = "#452753", bg = "#DEBEEF"},
CursorIM = {link = "Cursor"},
WildMenu = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorColumn = {bg = "#563168"},
CursorLine = {link = "CursorColumn"},
CursorLineNr = {fg = "#F47CC4", bg = "#563168", bold = true},
["@debug"] = {link = "Debug"},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
Delimiter = {fg = "#E250A8"},
["@punctuation"] = {link = "Delimiter"},
DiagnosticError = {fg = "#EF434C"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#E250A8"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#B4CFF8"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#B6CA68"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticUnderlineError = {fg = "#EF434C", underline = true},
DiagnosticUnderlineHint = {fg = "#E250A8", underline = true},
DiagnosticUnderlineInfo = {fg = "#B4CFF8", underline = true},
DiagnosticUnderlineOk = {fg = "#B6CA68", underline = true},
DiagnosticUnderlineWarn = {fg = "#F4D07C", underline = true},
DiagnosticWarn = {fg = "#F4D07C"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#452753", bg = "#B6CA68", bold = true},
DiffChange = {fg = "#452753", bg = "#7CACF4", bold = true},
DiffDelete = {fg = "#452753", bg = "#EF434C", bold = true},
DiffText = {fg = "#E250A8", bold = true, italic = true},
Directory = {fg = "#A684EB"},
EndOfBuffer = {fg = "#826490"},
Error = {fg = "#452753", bg = "#EF434C"},
ErrorMsg = {fg = "#F47C82", bg = "#563168"},
["@exception"] = {link = "Exception"},
["@float"] = {link = "Float"},
FloatTitle = {fg = "#DEBEEF", bold = true},
FoldColumn = {fg = "#784592"},
CursorLineFold = {link = "FoldColumn"},
CursorLineSign = {link = "FoldColumn"},
Folded = {fg = "#DEBEEF", bg = "#331D3E"},
Function = {fg = "#B4CFF8"},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
GitSignsAdd = {fg = "#CCDA95"},
GitSignsChange = {fg = "#B4CFF8"},
GitSignsDelete = {fg = "#F47C82"},
Identifier = {fg = "#A684EB"},
["@field"] = {link = "Identifier"},
["@namespace"] = {link = "Identifier"},
["@parameter"] = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
Ignore = {fg = "#A181B1"},
Search = {link = "IncSearch"},
["@include"] = {link = "Include"},
["@keyword"] = {link = "Keyword"},
["@label"] = {link = "Label"},
LineNr = {fg = "#C895DA", bg = "#6B3B7D"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
["@function.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
MatchParen = {fg = "#F47CC4", bg = "#6B3B7D", bold = true},
MiniDiffSignAdd = {fg = "#CCDA95", italic = true},
MiniDiffSignChange = {fg = "#B4CFF8", italic = true},
MiniDiffSignDelete = {fg = "#F47C82", italic = true},
MiniStatuslineDevinfo = {fg = "#DEBEEF", bg = "#563168"},
MiniStatuslineFileinfo = {link = "MiniStatuslineDevinfo"},
MiniStatuslineInactive = {fg = "#C895DA", bg = "#2E1A37"},
MiniStatuslineModeCommand = {fg = "#673B7D", bg = "#F47CC4"},
MiniStatuslineModeInsert = {fg = "#673B7D", bg = "#DEBEEF"},
MiniStatuslineModeNormal = {fg = "#DEBEEF", bg = "#8F4EA6"},
MiniStatuslineModeOther = {fg = "#563168", bg = "#CCDA95"},
MiniStatuslineModeReplace = {fg = "#673B7D", bg = "#F47C82"},
MiniStatuslineModeVisual = {fg = "#563168", bg = "#F4D07C"},
MiniTablineModifiedCurrent = {fg = "#452753", bg = "#C895DA", bold = true, italic = true},
MiniTablineModifiedHidden = {fg = "#826490", bg = "#331D3E", bold = true},
MiniTablineModifiedVisible = {fg = "#BCA5E9", bg = "#563168", bold = true},
MiniTablineVisible = {fg = "#BCA5E9", bg = "#563168"},
ModeMsg = {fg = "#DEBEEF", bold = true},
MoreMsg = {fg = "#784592"},
MsgArea = {fg = "#DEBEEF"},
MsgSeparator = {fg = "#452753", bg = "#A181B1"},
NonText = {fg = "#826490"},
NormalFloat = {fg = "#A181B1", bg = "#331D3E"},
FloatBorder = {link = "NormalFloat"},
NormalNC = {fg = "#826490"},
["@number"] = {link = "Number"},
Operator = {fg = "#F4D07C"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#DEBEEF", bg = "#331D3E"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {link = "Pmenu"},
PmenuSel = {fg = "#331D3E", bg = "#DEBEEF"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {fg = "#EBD6F5", bg = "#826490"},
PreProc = {fg = "#BCA5E9"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Question = {fg = "#F47CC4"},
QuickFixLine = {link = "Question"},
RenderMarkdownH1Bg = {fg = "#E250A8", bg = "#563168"},
RenderMarkdownH2Bg = {fg = "#7CACF4", bg = "#563168"},
RenderMarkdownH3Bg = {fg = "#EFBB43", bg = "#563168"},
RenderMarkdownH4Bg = {fg = "#EF434C", bg = "#563168"},
RenderMarkdownH5Bg = {fg = "#B6CA68", bg = "#563168"},
RenderMarkdownH6Bg = {fg = "#A684EB", bg = "#563168"},
["@repeat"] = {link = "Repeat"},
SignColumn = {bg = "#472753"},
Special = {fg = "#F47CC4"},
Debug = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
["@constant.builtin"] = {link = "Special"},
["@constructor"] = {link = "Special"},
["@function.builtin"] = {link = "Special"},
SpecialChar = {fg = "#CCDA95"},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
SpecialKey = {fg = "#A181B1"},
SpellBad = {fg = "#EF434C", undercurl = true},
SpellCap = {fg = "#B4CFF8", undercurl = true},
SpellLocal = {fg = "#CCDA95", undercurl = true},
SpellRare = {fg = "#EFBB43", undercurl = true},
Statement = {fg = "#F47C82", bold = true},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLineNC = {bg = "#2E1A37"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#BCA5E9"},
["@string"] = {link = "String"},
["@structure"] = {link = "Structure"},
Substitute = {fg = "#673B7D", bg = "#EFBB43"},
TabLine = {fg = "#826490", bg = "#331D3E"},
MiniTablineHidden = {link = "TabLine"},
TabLineFill = {bg = "#2E1A37"},
MiniTablineFill = {link = "TabLineFill"},
TabLineSel = {fg = "#452753", bg = "#C895DA", italic = true},
MiniTablineCurrent = {link = "TabLineSel"},
["@tag"] = {link = "Tag"},
TermCursor = {fg = "#452753", bg = "#A181B1"},
TermCursorNC = {fg = "#A181B1"},
Title = {bold = true},
["@text.title"] = {link = "Title"},
Todo = {bold = true},
["@text.todo"] = {link = "Todo"},
TroubleIndent = {fg = "#8F4EA6", bg = "#331D3E"},
TroublePos = {fg = "#8F4EA6", bg = "#331D3E"},
Type = {fg = "#7CACF4"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@type"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
VertSplit = {fg = "#563168"},
Winseparator = {link = "VertSplit"},
Visual = {fg = "#452753", bg = "#C895DA"},
LspReferenceRead = {link = "Visual"},
LspReferenceText = {link = "Visual"},
LspReferenceWrite = {link = "Visual"},
LspSignatureActiveParameter = {link = "Visual"},
VisualNOS = {fg = "#DEBEEF", bg = "#6B3B7D"},
WarningMsg = {fg = "#BCA5E9"},
Whitespace = {fg = "#784592"},
WinBar = {bg = "#2E1A37", bold = true},
WinBarNC = {bg = "#2E1A37"},
		-- PATCH_CLOSE
	}
	local opts = require("luna").opts
	if opts.transparent then
		theme["Normal"].bg = "none"
		theme["StatusLine"].bg = "none"
	end
	if opts.overrides ~= false then
		theme = vim.tbl_deep_extend("force", theme, opts.overrides)
	end
	return theme
end
return luna

