luna = {}
---@return table
luna.build = function()
	local theme = {
		-- PATCH_OPEN
Normal = {fg = "#DBC8E5", bg = "#432B50"},
MiniStatuslineFilename = {link = "Normal"},
StatusLine = {link = "Normal"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#8DAFE2"},
Boolean = {link = "Character"},
Float = {link = "Character"},
Number = {link = "Character"},
["@character"] = {link = "Character"},
ColorColumn = {bg = "#654077"},
Comment = {fg = "#826490", italic = true},
LspCodeLens = {link = "Comment"},
LspCodeLensSeparator = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Conceal = {fg = "#826490"},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#EFBB43"},
["@constant"] = {link = "Constant"},
CurSearch = {fg = "#543663", bg = "#F4D07C"},
IncSearch = {link = "CurSearch"},
Cursor = {fg = "#432B50", bg = "#DBC8E5"},
CursorIM = {link = "Cursor"},
WildMenu = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorColumn = {bg = "#543663"},
CursorLine = {link = "CursorColumn"},
CursorLineNr = {fg = "#EB84C2", bg = "#543663", bold = true},
["@debug"] = {link = "Debug"},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
Delimiter = {fg = "#A98DE2"},
["@punctuation"] = {link = "Delimiter"},
DiagnosticError = {fg = "#D3222B"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#D65CA5"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#B9D0F4"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#B6CA68"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticUnderlineError = {fg = "#D3222B", underline = true},
DiagnosticUnderlineHint = {fg = "#D65CA5", underline = true},
DiagnosticUnderlineInfo = {fg = "#B9D0F4", underline = true},
DiagnosticUnderlineOk = {fg = "#B6CA68", underline = true},
DiagnosticUnderlineWarn = {fg = "#F4D07C", underline = true},
DiagnosticWarn = {fg = "#F4D07C"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#432B50", bg = "#B6CA68", bold = true},
DiffChange = {fg = "#432B50", bg = "#8DAFE2", bold = true},
DiffDelete = {fg = "#432B50", bg = "#D3222B", bold = true},
DiffText = {fg = "#D65CA5", bold = true, italic = true},
Directory = {fg = "#A98DE2"},
EndOfBuffer = {fg = "#826490"},
Error = {fg = "#432B50", bg = "#D3222B"},
ErrorMsg = {fg = "#E25057", bg = "#543663"},
["@exception"] = {link = "Exception"},
["@float"] = {link = "Float"},
FloatTitle = {fg = "#DBC8E5", bold = true},
FoldColumn = {fg = "#764B8B"},
CursorLineFold = {link = "FoldColumn"},
CursorLineSign = {link = "FoldColumn"},
Folded = {fg = "#DBC8E5", bg = "#32203C"},
Function = {fg = "#D65CA5"},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
GitSignsAdd = {fg = "#CCDA95"},
GitSignsChange = {fg = "#B9D0F4"},
GitSignsDelete = {fg = "#E25057"},
Identifier = {fg = "#EB84C2"},
["@field"] = {link = "Identifier"},
["@namespace"] = {link = "Identifier"},
["@parameter"] = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
Ignore = {fg = "#A181B1"},
Search = {link = "IncSearch"},
["@include"] = {link = "Include"},
["@keyword"] = {link = "Keyword"},
["@label"] = {link = "Label"},
LineNr = {fg = "#CFAFDE", bg = "#634672"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
["@function.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
MatchParen = {fg = "#EB84C2", bg = "#634672", bold = true},
MiniDiffSignAdd = {fg = "#CCDA95", italic = true},
MiniDiffSignChange = {fg = "#B9D0F4", italic = true},
MiniDiffSignDelete = {fg = "#E25057", italic = true},
MiniStatuslineDevinfo = {fg = "#DBC8E5", bg = "#543663"},
MiniStatuslineFileinfo = {link = "MiniStatuslineDevinfo"},
MiniStatuslineInactive = {fg = "#CFAFDE", bg = "#2D1D35"},
MiniStatuslineModeCommand = {fg = "#654077", bg = "#EB84C2"},
MiniStatuslineModeInsert = {fg = "#654077", bg = "#DBC8E5"},
MiniStatuslineModeNormal = {fg = "#DBC8E5", bg = "#845D98"},
MiniStatuslineModeOther = {fg = "#543663", bg = "#CCDA95"},
MiniStatuslineModeReplace = {fg = "#654077", bg = "#E25057"},
MiniStatuslineModeVisual = {fg = "#543663", bg = "#F4D07C"},
MiniTablineModifiedCurrent = {fg = "#432B50", bg = "#CFAFDE", bold = true, italic = true},
MiniTablineModifiedHidden = {fg = "#826490", bg = "#32203C", bold = true},
MiniTablineModifiedVisible = {fg = "#C0A7F1", bg = "#543663", bold = true},
MiniTablineVisible = {fg = "#C0A7F1", bg = "#543663"},
ModeMsg = {fg = "#DBC8E5", bold = true},
MoreMsg = {fg = "#764B8B"},
MsgArea = {fg = "#DBC8E5"},
MsgSeparator = {fg = "#432B50", bg = "#A181B1"},
NonText = {fg = "#826490"},
NormalFloat = {fg = "#A181B1", bg = "#32203C"},
FloatBorder = {link = "NormalFloat"},
NormalNC = {fg = "#826490"},
["@number"] = {link = "Number"},
Operator = {fg = "#F4D07C"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#DBC8E5", bg = "#32203C"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {link = "Pmenu"},
PmenuSel = {fg = "#32203C", bg = "#DBC8E5"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {fg = "#EAD9F2", bg = "#826490"},
PreProc = {fg = "#A98DE2"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Question = {fg = "#EB84C2"},
QuickFixLine = {link = "Question"},
RenderMarkdownH1Bg = {fg = "#432B50", bg = "#D65CA5"},
RenderMarkdownH2Bg = {fg = "#432B50", bg = "#8DAFE2"},
RenderMarkdownH3Bg = {fg = "#432B50", bg = "#EFBB43"},
RenderMarkdownH4Bg = {fg = "#432B50", bg = "#D3222B"},
RenderMarkdownH5Bg = {fg = "#432B50", bg = "#B6CA68"},
RenderMarkdownH6Bg = {fg = "#432B50", bg = "#A98DE2"},
["@repeat"] = {link = "Repeat"},
SignColumn = {bg = "#422F4C"},
Special = {fg = "#C0A7F1"},
Debug = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
["@constant.builtin"] = {link = "Special"},
["@constructor"] = {link = "Special"},
["@function.builtin"] = {link = "Special"},
SpecialChar = {fg = "#CCDA95"},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
SpecialKey = {fg = "#A181B1"},
SpellBad = {fg = "#D3222B", undercurl = true},
SpellCap = {fg = "#B9D0F4", undercurl = true},
SpellLocal = {fg = "#CCDA95", undercurl = true},
SpellRare = {fg = "#EFBB43", undercurl = true},
Statement = {fg = "#E25057", bold = true},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLineNC = {bg = "#2D1D35"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#B6CA68"},
["@string"] = {link = "String"},
["@structure"] = {link = "Structure"},
Substitute = {fg = "#654077", bg = "#EFBB43"},
TabLine = {fg = "#826490", bg = "#32203C"},
MiniTablineHidden = {link = "TabLine"},
TabLineFill = {bg = "#2D1D35"},
MiniTablineFill = {link = "TabLineFill"},
TabLineSel = {fg = "#432B50", bg = "#CFAFDE", italic = true},
MiniTablineCurrent = {link = "TabLineSel"},
["@tag"] = {link = "Tag"},
TermCursor = {fg = "#432B50", bg = "#A181B1"},
TermCursorNC = {fg = "#A181B1"},
Title = {bold = true},
["@text.title"] = {link = "Title"},
Todo = {bold = true},
["@text.todo"] = {link = "Todo"},
TroubleIndent = {fg = "#845D98", bg = "#32203C"},
TroublePos = {fg = "#845D98", bg = "#32203C"},
Type = {fg = "#8DAFE2"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@type"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
VertSplit = {fg = "#543663"},
Winseparator = {link = "VertSplit"},
Visual = {fg = "#432B50", bg = "#CFAFDE"},
LspReferenceRead = {link = "Visual"},
LspReferenceText = {link = "Visual"},
LspReferenceWrite = {link = "Visual"},
LspSignatureActiveParameter = {link = "Visual"},
VisualNOS = {fg = "#DBC8E5", bg = "#634672"},
WarningMsg = {fg = "#C0A7F1"},
Whitespace = {fg = "#764B8B"},
WinBar = {bg = "#2D1D35", bold = true},
WinBarNC = {bg = "#2D1D35"},
		-- PATCH_CLOSE
	}
	local opts = require("luna").opts
	if opts.transparent then
		theme["Normal"].bg = "none"
		theme["StatusLine"].bg = "none"
	end
	if opts.overrides ~= false then
		theme = vim.tbl_deep_extend("force", theme, opts.overrides)
	end
	return theme
end
return luna

