# luna v0.2.1 by sailorfe
# built 2026-03-04
# https://codeberg.org/sailorfe/luna.nvim

[colors.primary]
background = "#271B2D"
foreground = "#EAD9F2"

[colors.normal]
black = "#372640"
red = "#F07575"
green = "#D1F075"
yellow = "#F0D175"
blue = "#7DB2E8"
magenta = "#B27DE8"
cyan = "#E87DB3"
white = "#EAD9F2"

[colors.bright]
black = "#483253"
red = "#FA9E9E"
green = "#E3FA9E"
yellow = "#FAE39E"
blue = "#A3CCF5"
magenta = "#CCA3F5"
cyan = "#F5A3CC"
white = "#F8EBFF"
