# -----------------------------------------------------------------------------
# Luna Alacritty Colors
# Theme: Luna
# Upstream: https://codeberg.org/sailorfe/luna.nvim/src/branch/main/extras/alacritty/luna.toml
# -----------------------------------------------------------------------------

[env]
term = "xterm-256color"

[font]
normal = { family = "Cozette" }
size = 11.0

[window]
dimensions = { columns = 120, lines = 28 }

[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = '#271b2d'
foreground = '#ead9f2'

#[colors.cursor]
#cursor = '#ead9f2'
#text = '#271b2d'

# Normal colors
[colors.normal]
black = '#372640'
red = '#f07575'
green = '#d1f075'
yellow = '#f0d175'
blue = '#7db2e8'
magenta = '#b27de8'
cyan = '#e87db3'
white = '#ead9f2'

# Bright colors
[colors.bright]
black = '#483253'
red = '#fa9e9e'
green = '#e3fa9e'
yellow = '#fae39e'
blue = '#a3ccf5'
magenta = '#cca4f5'
cyan = '#f5a3cc'
white = '#f8ebff'
