# -----------------------------------------------------------------------------
# Luna Alacritty Colors
# Theme: Luna
# Upstream: https://codeberg.org/sailorfe/luna.nvim/src/branch/main/extras/alacritty/luna.toml
# -----------------------------------------------------------------------------

[env]
term = "xterm-256color"

[font]
normal = { family = "Cozette" }
size = 11.0

[window]
dimensions = { columns = 120, lines = 28 }

[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = '#432b50'
foreground = '#dbc8e5'

#[colors.cursor]
#cursor = '#dbc8e5'
#text = '#432b50'

# Normal colors
[colors.normal]
black = '#543663'
red = '#e25057'
green = '#b6ca68'
yellow = '#efbb43'
blue = '#8dafe2'
magenta = '#a98de2'
cyan = '#d65c85'
white = '#dbc8e5'

# Bright colors
[colors.bright]
black = '#764b8b'
red = '#f8777e'
green = '#ccda95'
yellow = '#f4d07c'
blue = '#b9d0f4'
magenta = '#c0a7f1'
cyan = '#eb84c2'
white = '#ead9f2'
