#-*- luna

[colors]
foreground= dbc8e5
background= 37273f
selection-background=   c0a7f1
selection-foreground=   37272f
urls=		b9d0f4

regular0=   4d3659
regular1=   e25057
regular2=   b6ca68
regular3=   efbb43
regular4=		8dafe2
regular5=		a98de2
regular6=   d65c85
regular7=		dbc8e5

bright0=		583e65
bright1=    eb8489
bright2=    ccda95
bright3=    f4d07c
bright4=    b9d0f4
bright5=    c0a7f1
bright6=    eb84c2
bright7=    ead9f2
