#-*- luna

[colors]
foreground= ead9f2
background= 271b2d
selection-background=   b27de8
selection-foreground=   271b2d
urls=		7db2e8
flash=	b27de8

regular0=   372640
regular1=   f07575
regular2=   d1f075
regular3=   f0d175
regular4=		7db2e8
regular5=		b27de8
regular6=   e87db3
regular7=		dbc8e5

bright0=		483253
bright1=    fd9696
bright2=    e3fd96
bright3=    fde396
bright4=    9dc9f6
bright5=    c99df6
bright6=    f69dca
bright7=    f8ebff
