# -*- luna tty colors -*-

if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0271B2D"
    echo -en "\x1b]P1F07575"
    echo -en "\x1b]P2D1F075"
    echo -en "\x1b]P3F0D175"
    echo -en "\x1b]P47DB2E8"
    echo -en "\x1b]P5B27DE8"
    echo -en "\x1b]P6E87DB3"
    echo -en "\x1b]P7F8EBFF"
    echo -en "\x1b]P8483253"
    echo -en "\x1b]P9FA9E9E"
    echo -en "\x1b]PAE3FA9E"
    echo -en "\x1b]PBFAE39E"
    echo -en "\x1b]PCA3CCF5"
    echo -en "\x1b]PDCCA3F5"
    echo -en "\x1b]PEF5A3CC"
    echo -en "\x1b]PFEAD9F2"
    clear
fi