# luna v0.2.2 by sailorfe
# built 2026-03-18
# https://codeberg.org/sailorfe/luna.nvim

background: #271B2D
foreground: #EAD9F2

color0: #483253
color1: #F07575
color2: #D1F075
color3: #F0D175
color4: #7DB2E8
color5: #B27DE8
color6: #E87DB3
color7: #EAD9F2

color8: #7A5C8A
color9: #FA9E9E
color10: #E3FA9E
color11: #FAE39E
color12: #A3CCF5
color13: #CCA3F5
color14: #F5A3CC
color15: #F8EBFF
